export const APP_LOAD = 'APP_LOAD';

export const LOGIN = 'LOGIN';

export const ASYNC_START = 'ASYNC_START';
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const REDIRECT = 'REDIRECT';
export const LOGOUT = 'LOGOUT';

export const VALIDATION_ERROR = 'VALIDATION_ERROR';
export const UPDATE_FIELD_POINT = 'UPDATE_FIELD_POINT';
export const POINTS_LOADED = 'POINTS_LOADED';
export const POINTS_RECALCULATED = 'POINTS_RECALCULATED';
export const POINT_ADDED = 'POINT_ADDED';

export const CHANGE_COLORS = 'CHANGE_COLORS';
